language: node_js

node_js: 8

jobs:
  include:

    - stage: install, check code style and coverage
      services:
        - mongodb
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
        hosts:
          - localhost
      before_install:
        - sudo apt-get update && sudo apt-get install sendmail python make g++
      before_script:
        - npm install -g grunt-cli
        - sleep 10
      script:
        - grunt
        - if [ "$TRAVIS_BRANCH" != "master" ]; then grunt test; fi
        - if [ "$TRAVIS_BRANCH" = "master" ]; then grunt coverage; fi

    - stage: Publish to npm
      if: branch = master
      script:
        - echo "PUBLISH npm"

    - stage: Publish to docker registry
      if: branch = master
      script:
      - echo "PUBLISH docker"
      - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
      - export MAJOR_VERSION=$(echo ${PACKAGE_VERSION} | awk -F. '{ print $1 }')
      - echo Package version ${PACKAGE_VERSION}
      - echo Major version ${MAJOR_VERSION}
      - docker login -u $docker_username -p $docker_password
      - docker build -t gateway .
      - docker tag gateway:latest ${docker_username}/gateway:${PACKAGE_VERSION}
      - docker tag gateway:latest ${docker_username}/gateway:${MAJOR_VERSION}
      - docker push ${docker_username}/soajsgodemo