language: node_js

node_js: 8

services:
  - mongodb

env:
  - CXX=g++-4.8

jobs:
  include:
    - stage: install & check code style
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
        hosts:
          - localhost
      before_install:
        - sudo apt-get update && sudo apt-get install sendmail python make g++
      before_script:
        - npm install -g grunt-cli
        - sleep 10
      script:
        - grunt
    - stage: test and check coverage
      script:
      - grunt coverage
    - stage: Publish to npm
      if: branch = master
      script:
        -echo "npm master --next"